development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL"){'ws://localhost:3000/cable' }%>
test:
  adapter: async

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: disOrder_production
